language: python
sudo: false
python:
  - '2.7'
virtualenv:
  system_site_packages: false
addons:
  apt:
    packages:
      - python-pip
      - libhdf5-serial-dev
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.ccache"
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
install:
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - flake8 .
