dist: trusty
sudo: required

language: python

virtualenv:
  system_site_packages: false

addons:
  apt:
    packages:
      - python-pip

cache:
  ccache: true
  pip: true
  directories:
    - "$HOME/.ccache"
    - "$HOME/simphony"
    - "/var/cache/apt/archives"

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - git clone --branch=0.3.1 https://github.com/simphony/simphony-framework.git $HOME/simphony-framework
  - pushd $HOME/simphony-framework
  - sudo make base
  - sudo make apt-openfoam-deps
  - sudo make apt-simphony-deps
#  - sudo make apt-lammps-deps
#  - sudo make fix-pip
#  - sudo make apt-mayavi-deps
#  - sudo ln -s ccache /usr/local/bin/mpic++
#  - make simphony-env
#  - make lammps
#  - source ~/simphony/bin/activate
#  - make simphony-common
#  - make simphony-mayavi
#  - make simphony-openfoam
#  - make simphony-liggghts
#  - make simphony-lammps
#  - popd
install:
#  - pip install -r dev_requirements.txt
#  - python -c "import simphony"
script:
#  - flake8 .
